import Head from "next/head";
import Image from "next/image";
import Liquid from "../../public/assets/backgroundLiquid.gif";

export default function Home() {
  return (
    <>
      <Head>
        <title>CodeWiseClone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-white z-0 w-screen h-screen">
          <Image
            className="blur-2xl"
            src={Liquid}
            alt="Liquid"
            fill
            quality={100}
            style={{
              position: "absolute",
              top: "0",
              left: "0",
            }}
          />
        </div>
      </main>
    </>
  );
}
